
import React from 'react';
import { Link } from 'react-router-dom';

const ArchitectureOverview: React.FC = () => {
  return (
    <div className="max-w-5xl mx-auto py-16 px-8">
      <header className="text-center mb-16">
        <h1 className="text-4xl font-extrabold text-slate-900 tracking-tight sm:text-5xl">
          SunAI Agency Platform Plan
        </h1>
        <p className="mt-4 text-lg text-slate-500 max-w-2xl mx-auto">
          The foundation of a high-performance, AI-assisted operations platform.
        </p>
        <div className="mt-8">
          <Link to="/app/projects" className="bg-slate-900 text-white px-6 py-3 rounded-lg font-bold hover:bg-slate-800 transition-colors">
            Go to Main Dashboard
          </Link>
        </div>
      </header>

      <section className="space-y-12">
        <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200">
          <h2 className="text-2xl font-bold text-slate-900 mb-4">1. System Overview</h2>
          <div className="prose prose-slate max-w-none text-slate-600 space-y-4">
            <p>
              SunAI Agency is an AI-powered operations platform designed to help agencies turn ambiguous project ideas into structured, executable workflows. 
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Project:</strong> The top-level container for work.</li>
              <li><strong>Wizard:</strong> A structured intake process to capture user intent and project constraints.</li>
              <li><strong>Blueprint:</strong> The resulting "Source of Truth" generated by the Wizard and confirmed by the user.</li>
              <li><strong>Intelligence:</strong> AI-driven interpretations and recommendations based on the Blueprint.</li>
              <li><strong>Execution:</strong> Versioned plans and tasks approved by humans for safe deployment.</li>
            </ul>
            <p className="text-sm italic bg-slate-50 p-4 rounded-lg border-l-4 border-blue-500">
              Setup order matters: Without a confirmed Blueprint, the AI cannot provide reliable Intelligence. We enforce a "Human-in-the-Loop" approval flow at every transition point.
            </p>
          </div>
        </div>

        <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200">
          <h2 className="text-2xl font-bold text-slate-900 mb-4">2. Core Entities</h2>
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50">
                  <th className="p-4 border-b border-slate-200 text-sm font-bold">Entity</th>
                  <th className="p-4 border-b border-slate-200 text-sm font-bold">Purpose</th>
                  <th className="p-4 border-b border-slate-200 text-sm font-bold">Created When</th>
                </tr>
              </thead>
              <tbody className="text-sm text-slate-600 divide-y divide-slate-100">
                <tr><td className="p-4 font-medium text-slate-900">User</td><td className="p-4">Authenticated person</td><td className="p-4">Signup</td></tr>
                <tr><td className="p-4 font-medium text-slate-900">Client</td><td className="p-4">External or internal customer</td><td className="p-4">Project creation</td></tr>
                <tr><td className="p-4 font-medium text-slate-900">Project</td><td className="p-4">Container for all work</td><td className="p-4">“New Project”</td></tr>
                <tr><td className="p-4 font-medium text-slate-900">Wizard Session</td><td className="p-4">Temporary intake state</td><td className="p-4">Wizard start</td></tr>
                <tr><td className="p-4 font-medium text-slate-900">Blueprint</td><td className="p-4">Confirmed project intent</td><td className="p-4">Wizard confirmation</td></tr>
                <tr><td className="p-4 font-medium text-slate-900">Project Intelligence</td><td className="p-4">Interpreted recommendations</td><td className="p-4">After Blueprint</td></tr>
                <tr><td className="p-4 font-medium text-slate-900">Execution Plan</td><td className="p-4">Versioned plan</td><td className="p-4">User approval</td></tr>
                <tr><td className="p-4 font-medium text-slate-900">Task</td><td className="p-4">Unit of work</td><td className="p-4">Execution Plan</td></tr>
                <tr><td className="p-4 font-medium text-slate-900">Audit Log</td><td className="p-4">Safety & traceability</td><td className="p-4">Any action</td></tr>
              </tbody>
            </table>
          </div>
        </div>

        <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200">
          <h2 className="text-2xl font-bold text-slate-900 mb-4">3. Routing Setup</h2>
          <div className="grid md:grid-cols-2 gap-8">
            <div>
              <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wide mb-3">Public</h3>
              <ul className="space-y-2 text-sm text-slate-600">
                <li><code>/</code> — Overview</li>
                <li><code>/login</code> — Auth</li>
                <li><code>/signup</code> — Auth</li>
              </ul>
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wide mb-3">App</h3>
              <ul className="space-y-2 text-sm text-slate-600">
                <li><code>/app/projects</code> — Dashboard</li>
                <li><code>/app/projects/:id</code> — Details</li>
                <li><code>/app/projects/:id/wizard</code> — Intent Capture</li>
                <li><code>/app/projects/:id/intelligence</code> — AI Projections</li>
                <li><code>/app/projects/:id/execution-plan</code> — Approved Tasks</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      <footer className="mt-20 pt-8 border-t border-slate-200 text-center text-slate-400 text-sm">
        SunAI Agency Architecture Proposal &copy; 2024
      </footer>
    </div>
  );
};

export default ArchitectureOverview;
